//
//  EditItemInteractor.swift
//  Listko
//
//  Created by David Tomic on 02/03/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditItemBusinessLogic
{
  func showListItems(request: EditItem.ShowListItems.Request)
}

protocol EditItemDataStore
{
  //var name: String { get set }
}

class EditItemInteractor: EditItemBusinessLogic, EditItemDataStore
{
  var presenter: EditItemPresentationLogic?
  var worker = EditItemWorker()
  
  func showListItems(request: EditItem.ShowListItems.Request)
  {
    let response = EditItem.ShowListItems.Response()
    presenter?.presentListItems(response: response)
  }
}
