//
//  EditItemPresenter.swift
//  Listko
//
//  Created by David Tomic on 02/03/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditItemPresentationLogic
{
  func presentListItems(response: EditItem.ShowListItems.Response)
}

class EditItemPresenter: EditItemPresentationLogic
{
  weak var viewController: EditItemDisplayLogic?
  
  func presentListItems(response: EditItem.ShowListItems.Response)
  {
    var listItems: [EditItem.ShowListItems.ViewModel.DisplayedListItem] = []
    
    
    
    let viewModel = EditItem.ShowListItems.ViewModel(listItems: listItems)
    viewController?.displayListItems(viewModel: viewModel)
  }
}
