//
//  ShowListPresenter.swift
//  Listko
//
//  Created by David Tomic on 08/03/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowListPresentationLogic
{
  func presentSomething(response: ShowList.Something.Response)
}

class ShowListPresenter: ShowListPresentationLogic
{
  weak var viewController: ShowListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowList.Something.Response)
  {
    let viewModel = ShowList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
