//
//  ListGroceryModels.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListGrocery
{
  // MARK: Use cases
  
  enum Fetch
  {
    struct Request
    {
    }
    struct Response
    {
      var listGroceries: [GroceryList]
    }
    struct ViewModel
    {
      struct DisplayedListGrocery {
        var title: String
        var subtitle: String
      }
      
      var displayedListGroceries: [DisplayedListGrocery]
    }
  }
}
