//
//  ListGroceryViewController.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwipeCellKit

protocol ListGroceryDisplayLogic: class
{
  func displayListGrocery(viewModel: ListGrocery.Fetch.ViewModel)
}

class ListGroceryViewController: ParentViewController, ListGroceryDisplayLogic
{
  var interactor: ListGroceryBusinessLogic?
  var router: (NSObjectProtocol & ListGroceryRoutingLogic & ListGroceryDataPassing)?
  
  let popupPresentAnimationController = PopupPresentAnimationController()
  let popupDismissAnimationController = PopupDismissAnimationController()

  var swipeOptions = SwipeTableOptions()
//{
//    var options = SwipeTableOptions()
//    options.transitionStyle = .border
//    options.buttonSpacing = 4
//    options.backgroundColor = #colorLiteral(red: 0.9467939734, green: 0.9468161464, blue: 0.9468042254, alpha: 1)
//    return options
//  }
  
  var displayItems: [ListGrocery.Fetch.ViewModel.DisplayedListGrocery] = []
  
  @IBOutlet weak var tableView: UITableView!
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    setupTableView()
    setLargeTextStyle()
    clearNavigationBarBackground()
    fetchListGrocery()


//    try! App.realm.write {
//      App.realm.add(p)
//    }
//    let res = App.realm.objects(Person.self)
//    print("res \(res)")
//
//    print("res \(res[0].cars[0].name)")

//        try! App.realm.write {
//          App.realm.deleteAll()
//        }

    
//    let listItem = ListItem()
//    listItem.title = "Title Test"
//
//    let item = ListItem.Item()
//    //item.itemId = 2
//    item.name = "item test"
//    listItem.items = [item]
//
//    listItem.commit()
//
//    let results : SRKResultSet = ListItem.query().fetch()
//    print("results \(results)")
    
    
    
    let gl = GroceryList()
    let listCategory = ListCategory()
    gl.listCategories.append(listCategory)
    print("gl \(gl)")
    
    print("gl \(gl.listCategories.first?.listItems.count)")
    
  }
  
  // MARK: Actions
  
  @IBAction func addListItem(_ sender: UIButton) {
    router?.routeToEditListItem(segue: nil)
  }
  
  
  // MARK: Methods
  
  private func fetchListGrocery()
  {
    let request = ListGrocery.Fetch.Request()
    interactor?.fetchListGrocery(request: request)
  }
  
  
  // MARK: Display
  
  func displayListGrocery(viewModel: ListGrocery.Fetch.ViewModel)
  {
    displayItems = viewModel.displayedListGroceries
    tableView.reloadData()
  }
}
