//
//  ListGroceryPresenter.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListGroceryPresentationLogic: PresenterProtocol
{
  func presentListGrocery(response: ListGrocery.Fetch.Response)
}

class ListGroceryPresenter: ListGroceryPresentationLogic
{
  weak var viewController: ListGroceryDisplayLogic?
  
  func presentListGrocery(response: ListGrocery.Fetch.Response)
  {
    var displayItems: [ListGrocery.Fetch.ViewModel.DisplayedListGrocery] = []
    
    for listItem in response.listGroceries {
      let dli = ListGrocery.Fetch.ViewModel.DisplayedListGrocery(title: "Konzum", subtitle: "Mrkva, kruh, mlijeko")
      displayItems.append(dli)
    }
    
    let viewModel = ListGrocery.Fetch.ViewModel(displayedListGroceries: displayItems)
    viewController?.displayListGrocery(viewModel: viewModel)
  }
}
