//
//  ListItemsPresenterTests.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Listko
import XCTest

class ListItemsPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListItemsPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListItemsPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListItemsPresenter()
  {
    sut = ListItemsPresenter()
  }
  
  // MARK: Test doubles
  
  class ListItemsDisplayLogicSpy: ListItemsDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: ListItems.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = ListItemsDisplayLogicSpy()
    sut.viewController = spy
    let response = ListItems.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
