//
//  ListItemsInteractorTests.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Listko
import XCTest

class ListItemsInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListItemsInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListItemsInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListItemsInteractor()
  {
    sut = ListItemsInteractor()
  }
  
  // MARK: Test doubles
  
  class ListItemsPresentationLogicSpy: ListItemsPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: ListItems.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = ListItemsPresentationLogicSpy()
    sut.presenter = spy
    let request = ListItems.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
