//
//  ListItemsPresenter.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListItemsPresentationLogic
{
  func presentListItems(response: ListItems.Fetch.Response)
}

class ListItemsPresenter: ListItemsPresentationLogic
{
  weak var viewController: ListItemsDisplayLogic?
  
  func presentListItems(response: ListItems.Fetch.Response)
  {
    let viewModel = ListItems.Fetch.ViewModel()
    viewController?.displayListItems(viewModel: viewModel)
  }
}
