//
//  ListItemsWorker.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListItemsWorker
{
  func fetchListItems(success: @escaping ([GroceryList]) -> (), failure: @escaping (AppError) -> ())
  {
    App.rest.request(.getList()) { (result) in
      App.jsonWorker.handleJsonArray(result: result, success: success, failure: failure)
    }
  }
}
