//
//  ListItemsViewController.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListItemsDisplayLogic: class
{
  func displayListItems(viewModel: ListItems.Fetch.ViewModel)
}

class ListItemsViewController: ParentViewController, ListItemsDisplayLogic
{
  var interactor: ListItemsBusinessLogic?
  var router: (NSObjectProtocol & ListItemsRoutingLogic & ListItemsDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    clearNavigationBarBackground()
    fetchListItems()
  }
  
  func clearNavigationBarBackground() {
    clearNavBarBackground()
  }
  
  func fetchListItems()
  {
    let request = ListItems.Fetch.Request()
    interactor?.fetchListItems(request: request)
  }
  
  func displayListItems(viewModel: ListItems.Fetch.ViewModel)
  {
    
  }
}
