//
//  ListItemsRouter.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListItemsRoutingLogic
{
  func routeToEditListItem(segue: UIStoryboardSegue?)
}

protocol ListItemsDataPassing
{
  var dataStore: ListItemsDataStore? { get }
}

class ListItemsRouter: NSObject, ListItemsRoutingLogic, ListItemsDataPassing
{
  weak var viewController: ListItemsViewController?
  var dataStore: ListItemsDataStore?
  
  // MARK: Routing
  
  func routeToEditListItem(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! EditItemViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "EditItemViewController") as! EditItemViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: ListItemsViewController, destination: EditItemViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: ListItemsDataStore, destination: inout EditItemDataStore)
  {
    //destination.name = source.name
  }
}
