//
//  ListItemsPresenter.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListItemsPresentationLogic: PresenterProtocol
{
  func presentListItems(response: ListItems.Fetch.Response)
}

class ListItemsPresenter: ListItemsPresentationLogic
{
  weak var viewController: ListItemsDisplayLogic?
  
  func presentListItems(response: ListItems.Fetch.Response)
  {
    var displayItems: [ListItems.Fetch.ViewModel.DisplayedListItem] = []
    
    for listItem in response.listItems {
      let dli = ListItems.Fetch.ViewModel.DisplayedListItem(title: "Konzum", subtitle: "Mrkva, kruh, mlijeko")
      displayItems.append(dli)
    }
    
    let viewModel = ListItems.Fetch.ViewModel(displayedListItem: displayItems)
    viewController?.displayListItems(viewModel: viewModel)
  }
}
