//
//  ListItemsInteractor.swift
//  Listko
//
//  Created by David Tomic on 20/02/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListItemsBusinessLogic
{
  func fetchListItems(request: ListItems.Fetch.Request)
}

protocol ListItemsDataStore
{
  
}

class ListItemsInteractor: ListItemsBusinessLogic, ListItemsDataStore
{
  var presenter: ListItemsPresentationLogic?
  var worker = ListItemsWorker()

  
  func fetchListItems(request: ListItems.Fetch.Request)
  {
    let response = ListItems.Fetch.Response()
    presenter?.presentListItems(response: response)
  }
}
