//
//  SettingsInteractor.swift
//  Listko
//
//  Created by David Tomic on 05/04/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsBusinessLogic
{
  func getItems(request: Settings.Get.Request)
}

protocol SettingsDataStore
{
  
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore
{
  var presenter: SettingsPresentationLogic?
  var worker: SettingsWorker?

  
  func getItems(request: Settings.Get.Request)
  {
    worker = SettingsWorker()
    worker?.doSomeWork()
    
    let response = Settings.Get.Response()
    presenter?.presentItems(response: response)
  }
}
