//
//  SettingsPresenterTests.swift
//  Listko
//
//  Created by David Tomic on 05/04/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Listko_dev
import XCTest

class SettingsPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: SettingsPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupSettingsPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupSettingsPresenter()
  {
    sut = SettingsPresenter()
  }
  
  // MARK: Test doubles
  
  class SettingsDisplayLogicSpy: SettingsDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: Settings.Get.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = SettingsDisplayLogicSpy()
    sut.viewController = spy
    let response = Settings.Get.Response()
    
    // When
    sut.presentItems(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
