//
//  SettingsViewControllerTests.swift
//  Listko
//
//  Created by David Tomic on 05/04/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Listko_dev
import XCTest

class SettingsViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: SettingsViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupSettingsViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupSettingsViewController()
  {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "Main", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "SettingsViewController") as! SettingsViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: Test doubles
  
  class SettingsBusinessLogicSpy: SettingsBusinessLogic
  {
    var getItemsCalled = false
    
    func getItems(request: Settings.Get.Request)
    {
      getItemsCalled = true
    }
  }
  
  // MARK: Tests
  
  func testShouldGetItemsWhenViewIsLoaded()
  {
    // Given
    let spy = SettingsBusinessLogicSpy()
    sut.interactor = spy
    
    // When
    loadView()
    
    // Then
    XCTAssertTrue(spy.getItemsCalled, "viewDidLoad() should ask the interactor to get items")
  }
  
  func testDisplaySomething()
  {
    // Given
    let viewModel = Settings.Get.ViewModel()
    
    // When
    loadView()
    sut.displaySomething(viewModel: viewModel)
    
    // Then
    //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
  }
}
