//
//  EditGroceryInteractor.swift
//  Listko
//
//  Created by David Tomic on 02/03/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditGroceryBusinessLogic
{
  func showGroceryListToEdit(request: EditGrocery.Edit.Request)
  func saveGroceryList(request: EditGrocery.Save.Request)
}

protocol EditGroceryDataStore
{
  var groceryList: GroceryList? { get set }
}

class EditGroceryInteractor: EditGroceryBusinessLogic, EditGroceryDataStore
{
  var presenter: EditGroceryPresentationLogic?
  var worker = EditGroceryWorker()
  var groceryList: GroceryList?
  
  
  // MARK: - Edit Grocery
  
  func showGroceryListToEdit(request: EditGrocery.Edit.Request)
  {
    if let groceryList = groceryList {
      let response = EditGrocery.Edit.Response(groceryList: groceryList)
      presenter?.presentGroceryListToEdit(response: response)
    } else {
      groceryList = GroceryList()
      addDefaultCategoryAndItemToGroceryList(groceryList: groceryList!)
      let response = EditGrocery.Edit.Response(groceryList: groceryList!)
      presenter?.presentGroceryListToEdit(response: response)
    }
  }
  
  private func addDefaultCategoryAndItemToGroceryList(groceryList: GroceryList) {
    let listCategory = ListCategory()
    groceryList.listCategories.append(listCategory)
    let listItem = ListItem()
    listCategory.listItems.append(listItem)
  }
  
  // MARK: - Save Grocery
  
  func saveGroceryList(request: EditGrocery.Save.Request) {
    
  }
  
}
