//
//  EditGroceryModels.swift
//  Listko
//
//  Created by David Tomic on 02/03/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditGrocery
{
  // MARK: Use cases
  
  enum Edit
  {
    struct Request
    {
    }
    struct Response
    {
      var groceryList: GroceryList
    }
    struct ViewModel
    {
      var groceryName: String?
      var displayedListItems: [String : [DisplayedListItem]]
      var sections: [String]
    }
  }
  
  enum Save
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  
  // MARK: common
  
  struct DisplayedListItem {
    var name: String
  }

}
