//
//  ShowGroceryInteractor.swift
//  Listko
//
//  Created by David Tomic on 08/03/2018.
//  Copyright (c) 2018 Terminko. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowGroceryBusinessLogic
{
  func doSomething(request: ShowGrocery.GetList.Request)
}

protocol ShowGroceryDataStore
{
  //var name: String { get set }
}

class ShowGroceryInteractor: ShowGroceryBusinessLogic, ShowGroceryDataStore
{
  var presenter: ShowGroceryPresentationLogic?
  var worker: ShowGroceryWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowGrocery.GetList.Request)
  {
    worker = ShowGroceryWorker()
    worker?.doSomeWork()
    
    let response = ShowGrocery.GetList.Response()
    presenter?.presentSomething(response: response)
  }
}
